#!/usr/bin/env python3
"""Generate the repository content catalog from query headers and rule YAML."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "content-catalog.md"


def query_metadata(path: Path) -> dict[str, str]:
    metadata: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        match = re.match(r"// ([^:]+):\s*(.*)", line)
        if match:
            metadata[match.group(1)] = match.group(2)
        elif line and not line.startswith("//"):
            break
    return metadata


def cell(value: object) -> str:
    return str(value or "—").replace("|", "\\|").replace("\n", " ")


def build_catalog() -> str:
    lines = [
        "# Content Catalog",
        "",
        "This file is generated by `scripts/generate_catalog.py`. Do not edit it manually.",
        "",
        "## Queries",
        "",
        "| Query | Type | Tables | Severity | Validation | Related rule |",
        "|---|---|---|---|---|---|",
    ]
    for path in sorted((ROOT / "queries").rglob("*.kql")):
        metadata = query_metadata(path)
        relative = path.relative_to(ROOT).as_posix()
        link = f"[{relative}](../{relative})"
        lines.append(
            "| " + " | ".join(
                [
                    link,
                    cell(metadata.get("Query Type")),
                    cell(metadata.get("Tables")),
                    cell(metadata.get("Severity")),
                    cell(metadata.get("Validation Status")),
                    cell(metadata.get("Related Analytics Rule")),
                ]
            ) + " |"
        )
    lines.extend(
        [
            "",
            "## Analytics rules",
            "",
            "| Rule | Domain | Severity | Tables | ATT&CK | Version |",
            "|---|---|---|---|---|---|",
        ]
    )
    for path in sorted((ROOT / "analytics-rules").rglob("*.yaml")):
        rule = yaml.safe_load(path.read_text(encoding="utf-8"))
        relative = path.relative_to(ROOT).as_posix()
        link = f"[{cell(rule.get('name'))}](../{relative})"
        tables = sorted(
            {
                table
                for connector in rule.get("requiredDataConnectors", [])
                for table in connector.get("dataTypes", [])
            }
        )
        domain = path.parent.name
        lines.append(
            "| " + " | ".join(
                [
                    link,
                    cell(domain),
                    cell(rule.get("severity")),
                    cell(", ".join(tables)),
                    cell(", ".join(rule.get("relevantTechniques", []))),
                    cell(rule.get("version")),
                ]
            ) + " |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if the catalog is stale")
    args = parser.parse_args()
    generated = build_catalog()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            print("Content catalog is stale. Run: python3 scripts/generate_catalog.py")
            return 1
        print("Content catalog is current.")
        return 0
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"Generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
